framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
    templating:
        engines: ['twig', 'php']
    php_errors:
        log: true
