parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.util.uploader:
        class: App\Util\Uploader
        arguments: ['@doctrine.orm.entity_manager']
        public: true

    admin.societies:
        class: App\Admin\SocietiesAdmin
        arguments: [~, App\Entity\Society, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Admin', label: 'Sociétés' }
        public: true

    admin.investment_funds:
        class: App\Admin\InvestmentFundsAdmin
        arguments: [~, App\Entity\InvestmentFund, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Admin', label: "Fonds d'investissements" }
        public: true

    admin.articles:
        class: App\Admin\ArticlesAdmin
        arguments: [~, App\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Admin', label: 'Articles' }
        public: true

    admin.transactions:
        class: App\Admin\TransactionsAdmin
        arguments: [~, App\Entity\Transaction, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Admin', label: 'Transactions' }
        public: true
