parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.util.uploader:
        class: App\Util\Uploader
        public: true

    admin.societies:
        class: App\Admin\SocietyAdmin
        arguments: [~, App\Entity\Society, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Admin', label: 'Sociétés' }
        public: true

    admin.investment_funds:
        class: App\Admin\InvestmentFundAdmin
        arguments: [~, App\Entity\InvestmentFund, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Admin', label: "Fonds d'investissements" }
        public: true

    admin.articles:
        class: App\Admin\ArticleAdmin
        arguments: [~, App\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Admin', label: 'Articles' }
        public: true

    admin.transactions:
        class: App\Admin\TransactionAdmin
        arguments: [~, App\Entity\Transaction, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Admin', label: 'Transactions' }
        public: true

    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Admin', label: 'User' }
        public: true
